### ISSUE TITLE
Set up ES6 -> ES5 compilation

### ISSUE THREAD

**Issue by VincentCordobes** [js-republic/ReDoc#12]
Need babel.

Quid Node 6 & 7 which implement many es6 features

**Comment by mbreton** [comment]
I same time, could we think about the build cycle of the project.
How we build and release our tool ?
With which command ?
And which steps ?

For me a good build flow could be :
Lint -> Unit test -> transpile ES6 -> Integration test -> publish on NPM

With respectively the commands :
npm run lint -> npm test -- unit -> npm run build -> npm test -- integration -> npm publish 

What do you think about that ?

**Comment by PierrickGT** [comment]
It sounds go to me.

**Comment by VincentCordobes** [comment]
I don't think we need ES5 transpilation for now.  I suggest we close the issue and reopen it when we are ready to publish on npm.
