### ISSUE TITLE
Determine how tool on-boarding experience will be

### ISSUE THREAD

**Issue by mbreton** [js-republic/ReDoc#21]
This issue aims to determine how a user will use the tool. We must keep in mind that the on-boarding must be as simple as possible.
We are agree to say that the tool will be a simple module which will be installed as dev deps in the projects.
So, regarding other tools with the same shape like Eslint, Ava, Yarn ... I suggest that we expose two main commands in the tool :
- init : This command will generate a basic configuration by asking many questions to the user. This configuration could be saved in a specific conf file like a **.SGR.json** or in a **package.json** property
- run : This command will scan the project, extracts the component informations and finally generates the static asset of the documentation in a specific folder. This command could take some optional parameters.

The configuration could looks like this in first try :
```
{
    entry : 'main.js' // component entry point where will start the component scanning
    outputFolder : './component-docs' // folder where the doc will be generated
    type: 'react' // type of component. Possible value : react, angular2, vuejs, polymer
    additionalCssFile : './main.css' // additionalCssFile to load in the documentation, if the css is not embed
}
```

**Comment by PierrickGT** [comment]
I'm not sure we should allow people to add additional CSS files.
If we take React as an example, isn't all necessary CSS to style a component or a page imported in this component or at least in index.js ?

**Comment by mbreton** [comment]
An additional css file is not an expansive task and give more flexibility to user.
In React, we can embed the css with the component but it is not always the case, and by the way we will extract component from Angular 2, Vuejs, or Poylimer stack.
And It could possible that the user want load a theme for its documentation.

**Comment by mbreton** [comment]
I think we have all necessary informations to begin the init command implementation. By default are you ok to create the config into package.json ?

**Comment by PierrickGT** [comment]
You're right, may be it's a useful option to allow people to load an additional/external CSS file.
Let's add the config into package.json first and then we'll see if we create our own config file.

**Comment by mbreton** [comment]
I was thinking about the component scanning and maybe the entry point could not the best option. A scan with a top to bottom approach give us the possibility to retrieve all components used by the project whatever its shape (React.createClass, ES6 class or pure function). But we will find too the "container" components used by Redux or other business components. More over, if we take the case of a library of component, there is no entry point referencing all components.

I think we should prefer a bottom up approach. In details, we will scan all files in project, find every template's component (JSX syntax for React, @Component.template for the of Angular 2, etc) and ride up to retrieve the component containing this template. The benefit of this manner is we will retrieve any component containing html (whatever its shape too) and not business component. And there is no more necessary to reference this component from an entry point.

That sounds good ?

**Comment by VincentCordobes** [comment]
When you said entry point I thought you meant the project to scan. IMHO it's useless to try to scan component that are used in the project with  some kind of _top to bottom_ or _bottom to top_ approach. Why not just scan each project file, I keep only component that we are able to process ?

**Comment by mbreton** [comment]
Ok, but how do you detect if something is a component ? For me, we have to detect the template before to find the component attached to this template, right ?

**Comment by VincentCordobes** [comment]
I guess we can `docgen.parse(theContentOfAFile)` and check if it has been successfully parsed or not.

**Comment by mbreton** [comment]
You make a reference to react-docgen project, I guess !? I agree to try to use it, it seems very good, but if you try to scan a file without component the tool throws an error that we have to handle.

It's not really a problem, but I was thinking about a transverse solution, not only for React but Angular, Vue and other component frameworks.

So, we are both ok to remove the entry point from configuration.

**Comment by VincentCordobes** [comment]
I see your point, we could still replace docgen with something else in the future. 

Instead of an _entry point_ we could have an `inputDirectory` which is the root folder to scan (In case I know I have all my components in a specific directory, no need to parse the whole project) What do you think ?

**Comment by mbreton** [comment]
Perfect, I like the idea. Maybe we can too add a `ignore` field to give to the user the ability to not scan specific file or directory with a glob pattern ... 

The conf could look like that : 

```
{
    inputDir : './myProject' // project directory where will start the component scanning
    outputDir : './component-docs' // folder where the doc will be generated
    ignore : '/**/*.spec.js' // regex which define the file/directory to ignore
    type: 'react' // type of component. Possible value : react, angular2, vuejs, polymer
    additionalCssFile : './main.css' // additionalCssFile to load in the documentation, if the css is not embed
}
```
