### ISSUE TITLE
Create an init command on SGR tool

### ISSUE THREAD

**Issue by mbreton** [js-republic/ReDoc#22]
According what is saying in the #21 issue, this issue defines the creation of the **init** command on the SGR tool.

Pitch : 
As a user of the tool, I want to be able to run an **init** command likes `sgr init` in a terminal. This command will ask many questions to me to fill the configuration describes below and write it the _package.json_ under a 'sgrConfig' property : 
```
{
    inputDir : './myProject' // project directory where will start the component scanning
    outputDir : './component-docs' // folder where the doc will be generated
    ignore : '/**/*.spec.js' // regex which define the file/directory to ignore
    type: 'react' // type of component. Possible value : react, angular2, vuejs, polymer
    additionalCssFile : './main.css' // additionalCssFile to load in the documentation, if the css is not embed
}
```

The question could be like this : 
* **Where is located your projet ?** (default : ./)
* **Where the documentation should be generated ?** (default : ./component-docs)
* **Which pattern do you want ignore ?** (default : ./node_module/*)
* **What Kind of Component are you using** ? (possible values : react, angular2(not impl), polymer (not impl, vuejs (not implemented)
* **Path of an additional CSS file ?** (blank by default)

BDD : 
If I execute the `sgr init` and then I respond to the questions : 

1. `./src`
2. `./docs`
3. `./node_modules/**|*ignored_component*`
4. `react`
5. `./src/css/theme.css`

I should find in the _package.json_
```
sgrConfig: {
    inputDir : './src'
    outputDir : './docs'
    ignore : './node_modules/**|*ignored_component*'
    type: 'react'
    additionalCssFile : './src/css/theme.css'
}
```

**Comment by PierrickGT** [comment]
I don't think it's very user friendly to have to use a Regex in order to ignore files and folders.
Shouldn't we ignore some folders and files by default and then give the ability to users to add the folders and files they want to ignore in an array?

Something like:
```
ignore: ['./node_modules', '.gitignore', ...]
```
